<?php

namespace app\admin\controller;

use think\Request;
use app\admin\model\CateAttr as model;
/**
 * @title 分类属性
 * @description ...
 */
class Cateattr extends Paren
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @title 分类属性列表
     * @description
     * @author 
     * @url /admin/cateattr/lst
     * @method GET
     * @return data:返回分页列表
     */
    public function lst(Request $request,model $model){
        $param=$request->param();
        $where=[];
        if(isset($param['display'])){
            $where['display']=$param['display'];
        }

        $result=$model->lst($where);
        $this->result($result,200,'','json');
    }

    /**
     * @title 获取添加/编辑页面需要的数据
     * @description
     * @author 
     * @url /admin/cateattr/addpage
     * @method GET
     * @param 
     * @return data:返回信息
     */
    public function addpage(Request $request,model $model){
        $result=$model->addpage();
        $this->result($result['data'],$result['code'],'','json');
    }
    /**
     * @title 修改类型状态
     * @description
     * @author
     * @url /admin/cateattr/statusave
     * @method POST
     * @param 类型数据包
     * @return data:返回信息
     */
    public function statusave(Request $request,model $model){
        $param=$request->param();
        if($param['display']==1){
            $param['display']=0;
        }else{
            $param['display']=1;
        }
        $result=$model->setSave($param);
        $this->result('',$result['code'],$result['msg'],'json');
    }

    /**
     * @title 添加/编辑分类属性
     * @description
     * @author 
     * @url /admin/cateattr/add
     * @method POST
     * @param 类型数据包
     * @return data:返回信息
     */
    public function add(Request $request,model $model){
    //  self::adminAutho('test_add'); //权限验证，先注释
        $param=$request->param();
        $unique['require']='require';
        $unique['unique']='cate_attr,name';
        if(isset($param['id'])){
            $unique['unique']='cate_attr,name,'.$param['id'];
        }
        $validate=$this->validate($param,[
            'name|属性名'=>$unique
        ]);
        if(true !== $validate){
            $this->result('',0,$validate,'json');
        }

        $result=$model->setSave($param);
        $this->result('',$result['code'],$result['msg'],'json');
    }


    /**
     * @title 删除分类属性
     * @description
     * @author 
     * @url /admin/cateattr/del
     * @method GET
     * @return data:返回信息
     */
    public function del(Request $request,model $model){

    //  self::adminAutho('test_add'); //权限验证，先注释
        $id=$request->post('id');
        $result=$model->del($id);
        $this->result('',$result['code'],$result['msg'],'json');
    }
    /**
     * @title 获取属性详情
     * @description
     * @author
     * @url /admin/cateattr/desc
     * @method GET
     * @return data:返回信息
     */
    public function desc(Request $request,model $model){
        $id=$request->get('id',null);
        $data=$model->where('id',$id)->find();
        if(!empty($data['attr'])){
            $data['attr']=explode(',',$data['attr']);
        }

        $this->result($data,200,'','json');
    }
}
